% Get data
% Documentation generation
docString = sprintf(['This script processes volumetric data from the Allen Brain Atlas.\n', ...
                     'It retrieves the data, applies transformations, and visualizes the results.\n', ...
                     'Key functions used:\n', ...
                     '- getAllenTemplate: Retrieves the template volume data.\n', ...
                     '- nonzeros: Extracts non-zero elements from the volume data.\n', ...
                     '- V2v: Converts volume data to a vector format.\n', ...
                     '- getAllenTform: Provides transformation parameters for the volume.\n', ...
                     '- plotVolume: Visualizes the volume data.\n', ...
                     '- scat3: Creates a 3D scatter plot of the data points.\n', ...
                     'Resolution is set to 50, which determines the granularity of the data.\n', ...
                     'The output includes a visual representation of the volume and scatter plot.']);
disp(docString);

resolution = 50; 
V = getAllenTemplate([],resolution); 
d = nonzeros(V);

v = V2v(V,getAllenTform(resolution), 1, V > 0); 

% Plot
ss = (100/resolution); % step size
mask = repmat(diag([1, zeros(1,ss-1)]).* cat(3,1,zeros(1,1,ss-1)), size(V)./ss); % downsample just for plotting
figure;
nexttile; plotVolume(V.*cast(mask, 'like', V)); 
nexttile; scat3(v(1:(ss^3):end,:),[],d(1:(ss^3):end),'.'); axis image; xyzlabel; 

disp('You should see.....');