function out = getAllenLMask(varargin)
% GETALLENLMASK generates a logical mask for the Allen brain atlas.
% 
% Usage:
%   out = getAllenLMask(varargin)
%
% Inputs:
%   varargin - Variable input arguments that can be passed to the function.
%
% Outputs:
%   out - A logical array representing the left hemisphere mask of the Allen brain atlas.
%
% Description:
%   This function computes the left hemisphere mask based on the Allen brain atlas.
%   It utilizes the complementary right hemisphere mask generated by the 
%   getAllenRMask function. The output is a logical array where true values 
%   indicate the presence of the left hemisphere structures.
out = ~getAllenRMask(varargin{:}); 
end